### PR TITLE
Why not add support for naked generators?

### PR DESCRIPTION
**Pull request by refack**

### CODE REVIEW

**Comment by jonathanong** [comment]
because i generally just do `co(gen)`.

i was planning to go this route, but i always wanted to support gen funs as well as promises. just got lazy. if you create a PR supporting all those with tests i'm down

**Comment by refack** [comment]
On it

**Comment by refack** [comment]
Done

**Comment by jonathanong** [comment]
hmmm wanted generator functions + promises as well, but i can't argue with these tests... lol

**Comment by refack** [comment]
Promises I get, but how would you handle generator functions? Specifically ones with arguments? How would they get values?

**Comment by jonathanong** [comment]
meh it would just auto call it. not a big a deal. use-case is the generator equivalent of "closures"

**Comment by refack** [comment]
Done in #7

**Pull request merged**
